package opsi.sman35jkt.gathra.ui.theme

import androidx.compose.ui.graphics.Color

internal val ViridianLight = Color(0xFF006B5C)
internal val OnViridianLight = Color(0xFFFFFFFF)
internal val ViridianContainerLight = Color(0xFF77F8DC)
internal val OnViridianContainerLight = Color(0xFF00201A)
internal val VioletLight = Color(0xFF615B7B)
internal val OnVioletLight = Color(0xFFFFFFFF)
internal val VioletContainerLight = Color(0xFFE7DEFF)
internal val OnVioletContainerLight = Color(0xFF1D1734)
internal val AmberLight = Color(0xFF7C5800)
internal val OnAmberLight = Color(0xFFFFFFFF)
internal val AmberContainerLight = Color(0xFFFFDEA2)
internal val OnAmberContainerLight = Color(0xFF271900)
internal val BackgroundLight = Color(0xFFF8FAF7)
internal val OnBackgroundLight = Color(0xFF191C1B)
internal val SurfaceLight = Color(0xFFF8FAF7)
internal val SurfaceVariantLight = Color(0xFFDAE5E1)
internal val OnSurfaceVariantLight = Color(0xFF3F4946)
internal val OutlineLight = Color(0xFF6F7976)
internal val ErrorLight = Color(0xFFBA1A1A)

internal val ViridianDark = Color(0xFF56DBC0)
internal val OnViridianDark = Color(0xFF00382F)
internal val ViridianContainerDark = Color(0xFF005144)
internal val OnViridianContainerDark = Color(0xFF77F8DC)
internal val VioletDark = Color(0xFFCBC2E8)
internal val OnVioletDark = Color(0xFF322C4A)
internal val VioletContainerDark = Color(0xFF494262)
internal val OnVioletContainerDark = Color(0xFFE7DEFF)
internal val AmberDark = Color(0xFFF8BD48)
internal val OnAmberDark = Color(0xFF422C00)
internal val AmberContainerDark = Color(0xFF5E4200)
internal val OnAmberContainerDark = Color(0xFFFFDEA2)
internal val BackgroundDark = Color(0xFF101412)
internal val OnBackgroundDark = Color(0xFFE0E3E0)
internal val SurfaceDark = Color(0xFF101412)
internal val SurfaceVariantDark = Color(0xFF3F4946)
internal val OnSurfaceVariantDark = Color(0xFFBEC9C5)
internal val OutlineDark = Color(0xFF89938F)
internal val ErrorDark = Color(0xFFFFB4AB)

internal val RouteSelectedLight = Color(0xFF007D68)
internal val RouteAlternativeLight = Color(0xFF746D91)
internal val RouteCasingLight = Color(0xFFF7FFFC)
internal val OriginMarkerLight = Color(0xFF006B5C)
internal val DestinationMarkerLight = Color(0xFFB15D00)
internal val PendingMarkerLight = Color(0xFF4D3F86)

internal val RouteSelectedDark = Color(0xFF4DE1BF)
internal val RouteAlternativeDark = Color(0xFFC9BEF5)
internal val RouteCasingDark = Color(0xFF143C34)
internal val OriginMarkerDark = Color(0xFF56DBC0)
internal val DestinationMarkerDark = Color(0xFFFFB86B)
internal val PendingMarkerDark = Color(0xFFD0C3FF)
